import type {
  Achievement,
  CategoryBreakdown,
  DashboardStats,
  DuplicateGroup,
  LeakScoreBreakdown,
  MonthlySpending,
  PriceHike,
  Recommendation,
  SavingsGoal,
  Subscription,
  Transaction,
  UserProfile,
} from "@/types";

export const demoUser: UserProfile = {
  id: "user_1",
  name: "Alex Morgan",
  email: "alex.morgan@email.com",
  avatar: undefined,
  memberSince: "2025-11-15",
  totalSaved: 847.5,
};

export const demoSubscriptions: Subscription[] = [
  {
    id: "sub_1",
    name: "Netflix Premium",
    merchant: "Netflix",
    amount: 22.99,
    previousAmount: 15.49,
    frequency: "monthly",
    category: "streaming",
    lastCharge: "2026-07-01",
    nextCharge: "2026-08-01",
    isActive: true,
    priceHikePercent: 48.4,
    usageScore: 72,
    confidence: 0.98,
  },
  {
    id: "sub_2",
    name: "Spotify Premium",
    merchant: "Spotify",
    amount: 11.99,
    frequency: "monthly",
    category: "music",
    lastCharge: "2026-07-03",
    nextCharge: "2026-08-03",
    isActive: true,
    usageScore: 91,
    confidence: 0.99,
  },
  {
    id: "sub_3",
    name: "YouTube Music",
    merchant: "Google",
    amount: 10.99,
    frequency: "monthly",
    category: "music",
    lastCharge: "2026-07-05",
    nextCharge: "2026-08-05",
    isActive: true,
    isDuplicate: true,
    duplicateGroup: "music_streaming",
    usageScore: 23,
    confidence: 0.96,
  },
  {
    id: "sub_4",
    name: "Apple Music",
    merchant: "Apple",
    amount: 10.99,
    frequency: "monthly",
    category: "music",
    lastCharge: "2026-06-28",
    nextCharge: "2026-07-28",
    isActive: true,
    isDuplicate: true,
    duplicateGroup: "music_streaming",
    usageScore: 12,
    confidence: 0.94,
  },
  {
    id: "sub_5",
    name: "Amazon Prime",
    merchant: "Amazon",
    amount: 14.99,
    frequency: "monthly",
    category: "streaming",
    lastCharge: "2026-07-02",
    nextCharge: "2026-08-02",
    isActive: true,
    usageScore: 65,
    confidence: 0.97,
  },
  {
    id: "sub_6",
    name: "Disney+",
    merchant: "Disney",
    amount: 13.99,
    frequency: "monthly",
    category: "streaming",
    lastCharge: "2026-06-15",
    nextCharge: "2026-07-15",
    isActive: true,
    isDuplicate: true,
    duplicateGroup: "video_streaming",
    usageScore: 18,
    confidence: 0.95,
  },
  {
    id: "sub_7",
    name: "ChatGPT Plus",
    merchant: "OpenAI",
    amount: 20.0,
    frequency: "monthly",
    category: "software",
    lastCharge: "2026-07-10",
    nextCharge: "2026-08-10",
    isActive: true,
    usageScore: 88,
    confidence: 0.99,
  },
  {
    id: "sub_8",
    name: "Google One 200GB",
    merchant: "Google",
    amount: 2.99,
    frequency: "monthly",
    category: "cloud",
    lastCharge: "2026-07-01",
    nextCharge: "2026-08-01",
    isActive: true,
    usageScore: 45,
    confidence: 0.92,
  },
  {
    id: "sub_9",
    name: "Planet Fitness",
    merchant: "Planet Fitness",
    amount: 24.99,
    frequency: "monthly",
    category: "fitness",
    lastCharge: "2026-07-01",
    nextCharge: "2026-08-01",
    isActive: true,
    usageScore: 8,
    confidence: 0.93,
  },
  {
    id: "sub_10",
    name: "Adobe Creative Cloud",
    merchant: "Adobe",
    amount: 54.99,
    frequency: "monthly",
    category: "software",
    lastCharge: "2026-07-12",
    nextCharge: "2026-08-12",
    isActive: true,
    usageScore: 34,
    confidence: 0.98,
  },
  {
    id: "sub_11",
    name: "iCloud+ 2TB",
    merchant: "Apple",
    amount: 9.99,
    frequency: "monthly",
    category: "cloud",
    lastCharge: "2026-07-01",
    nextCharge: "2026-08-01",
    isActive: true,
    isDuplicate: true,
    duplicateGroup: "cloud_storage",
    usageScore: 55,
    confidence: 0.91,
  },
  {
    id: "sub_12",
    name: "NYT Digital",
    merchant: "New York Times",
    amount: 17.0,
    frequency: "monthly",
    category: "news",
    lastCharge: "2026-06-20",
    nextCharge: "2026-07-20",
    isActive: true,
    usageScore: 15,
    confidence: 0.89,
  },
];

export const demoPriceHikes: PriceHike[] = [
  {
    id: "ph_1",
    subscriptionId: "sub_1",
    merchant: "Netflix",
    oldAmount: 15.49,
    newAmount: 22.99,
    changePercent: 48.4,
    detectedAt: "2026-03-15",
    impact: "high",
  },
  {
    id: "ph_2",
    subscriptionId: "sub_5",
    merchant: "Amazon Prime",
    oldAmount: 12.99,
    newAmount: 14.99,
    changePercent: 15.4,
    detectedAt: "2026-01-01",
    impact: "medium",
  },
];

export const demoDuplicateGroups: DuplicateGroup[] = [
  {
    id: "dg_1",
    category: "Music Streaming",
    subscriptions: demoSubscriptions.filter((s) => s.duplicateGroup === "music_streaming"),
    monthlyWaste: 21.98,
    recommendation: "Keep Spotify (91% usage). Cancel YouTube Music and Apple Music.",
  },
  {
    id: "dg_2",
    category: "Video Streaming",
    subscriptions: demoSubscriptions.filter(
      (s) => s.duplicateGroup === "video_streaming" || s.merchant === "Netflix" || s.merchant === "Amazon"
    ),
    monthlyWaste: 27.98,
    recommendation: "Keep Netflix + Prime. Cancel Disney+ (18% usage).",
  },
  {
    id: "dg_3",
    category: "Cloud Storage",
    subscriptions: demoSubscriptions.filter((s) => s.duplicateGroup === "cloud_storage" || s.name.includes("Google One")),
    monthlyWaste: 9.99,
    recommendation: "Consolidate to Google One. Cancel iCloud+ 2TB.",
  },
];

export const demoRecommendations: Recommendation[] = [
  {
    id: "rec_1",
    action: "cancel",
    title: "Cancel Planet Fitness",
    description: "You visited the gym only 2 times in 90 days (8% usage score).",
    subscriptionId: "sub_9",
    merchant: "Planet Fitness",
    estimatedMonthlySavings: 24.99,
    estimatedAnnualSavings: 299.88,
    confidence: 0.94,
    reason: "Low usage detected — only 2 visits in 90 days vs $24.99/month cost.",
    priority: "high",
  },
  {
    id: "rec_2",
    action: "cancel",
    title: "Cancel Apple Music & YouTube Music",
    description: "Duplicate music subscriptions while Spotify has 91% usage.",
    merchant: "Apple / Google",
    estimatedMonthlySavings: 21.98,
    estimatedAnnualSavings: 263.76,
    confidence: 0.92,
    reason: "3 music streaming services detected. Spotify is your primary with 91% usage.",
    priority: "high",
  },
  {
    id: "rec_3",
    action: "downgrade",
    title: "Downgrade Netflix to Standard",
    description: "Premium tier may be unnecessary based on viewing patterns.",
    subscriptionId: "sub_1",
    merchant: "Netflix",
    estimatedMonthlySavings: 7.0,
    estimatedAnnualSavings: 84.0,
    confidence: 0.78,
    reason: "4K streaming detected on only 12% of sessions. Standard plan saves $7/month.",
    priority: "medium",
  },
  {
    id: "rec_4",
    action: "cancel",
    title: "Cancel NYT Digital",
    description: "News subscription with 15% engagement over 60 days.",
    subscriptionId: "sub_12",
    merchant: "New York Times",
    estimatedMonthlySavings: 17.0,
    estimatedAnnualSavings: 204.0,
    confidence: 0.87,
    reason: "Only 3 articles read in 60 days. Free alternatives available.",
    priority: "medium",
  },
  {
    id: "rec_5",
    action: "negotiate",
    title: "Negotiate Adobe Creative Cloud",
    description: "Loyal customer for 2+ years — eligible for retention discount.",
    subscriptionId: "sub_10",
    merchant: "Adobe",
    estimatedMonthlySavings: 15.0,
    estimatedAnnualSavings: 180.0,
    confidence: 0.71,
    reason: "Adobe typically offers 25-40% retention discounts. Usage at 34% suggests downgrade possible.",
    priority: "medium",
  },
  {
    id: "rec_6",
    action: "bundle",
    title: "Bundle Cloud Storage",
    description: "Merge iCloud+ and Google One into single provider.",
    estimatedMonthlySavings: 9.99,
    estimatedAnnualSavings: 119.88,
    confidence: 0.85,
    reason: "Paying for 2.2TB across two providers. Google One 200GB covers actual 87GB usage.",
    priority: "low",
  },
];

export const demoLeakScore: LeakScoreBreakdown = {
  overall: 42,
  unusedSubscriptions: 28,
  duplicateSubscriptions: 35,
  priceHikes: 52,
  largeExpenses: 45,
  spendingTrend: 38,
  reasoning: [
    "3 duplicate subscription groups costing $59.95/month",
    "Netflix price increased 48.4% ($7.50/month impact)",
    "Planet Fitness at 8% usage — $24.99/month waste",
    "Monthly subscription spend up 23% vs 6 months ago",
    "Adobe CC at 34% usage — consider downgrade",
  ],
};

export const demoDashboardStats: DashboardStats = {
  totalMonthlySpend: 216.9,
  activeSubscriptions: 12,
  potentialSavings: 96.96,
  leakScore: 42,
  highestExpense: { name: "Adobe Creative Cloud", amount: 54.99 },
  biggestPriceIncrease: { name: "Netflix", percent: 48.4 },
  annualWaste: 1163.52,
  projectedSavings: 1152.52,
};

export const demoMonthlySpending: MonthlySpending[] = [
  { month: "Feb", total: 178.5, subscriptions: 165.0, other: 13.5 },
  { month: "Mar", total: 185.2, subscriptions: 172.0, other: 13.2 },
  { month: "Apr", total: 192.8, subscriptions: 178.5, other: 14.3 },
  { month: "May", total: 198.4, subscriptions: 185.0, other: 13.4 },
  { month: "Jun", total: 205.1, subscriptions: 192.0, other: 13.1 },
  { month: "Jul", total: 216.9, subscriptions: 203.5, other: 13.4 },
];

export const demoCategoryBreakdown: CategoryBreakdown[] = [
  { category: "Software", amount: 74.99, count: 2, color: "#8b5cf6" },
  { category: "Streaming", amount: 51.97, count: 3, color: "#ef4444" },
  { category: "Fitness", amount: 24.99, count: 1, color: "#f59e0b" },
  { category: "Music", amount: 33.97, count: 3, color: "#10b981" },
  { category: "Cloud", amount: 12.98, count: 2, color: "#3b82f6" },
  { category: "News", amount: 17.0, count: 1, color: "#ec4899" },
  { category: "Other", amount: 1.0, count: 0, color: "#6b7280" },
];

export const demoTransactions: Transaction[] = [
  {
    id: "tx_1",
    merchant: "Netflix",
    date: "2026-07-01",
    amount: 22.99,
    category: "streaming",
    isRecurring: true,
    frequency: "monthly",
    confidence: 0.98,
  },
  {
    id: "tx_2",
    merchant: "Spotify",
    date: "2026-07-03",
    amount: 11.99,
    category: "music",
    isRecurring: true,
    frequency: "monthly",
    confidence: 0.99,
  },
  {
    id: "tx_3",
    merchant: "OpenAI",
    date: "2026-07-10",
    amount: 20.0,
    category: "software",
    isRecurring: true,
    frequency: "monthly",
    confidence: 0.99,
  },
  {
    id: "tx_4",
    merchant: "Adobe",
    date: "2026-07-12",
    amount: 54.99,
    category: "software",
    isRecurring: true,
    frequency: "monthly",
    confidence: 0.98,
  },
  {
    id: "tx_5",
    merchant: "Planet Fitness",
    date: "2026-07-01",
    amount: 24.99,
    category: "fitness",
    isRecurring: true,
    frequency: "monthly",
    confidence: 0.93,
  },
];

export const demoAchievements: Achievement[] = [
  {
    id: "ach_1",
    title: "First Scan",
    description: "Uploaded your first bank statement",
    icon: "Scan",
    unlocked: true,
    unlockedAt: "2025-11-15",
  },
  {
    id: "ach_2",
    title: "Leak Hunter",
    description: "Found $100+ in potential savings",
    icon: "Target",
    unlocked: true,
    unlockedAt: "2025-12-01",
  },
  {
    id: "ach_3",
    title: "Subscription Slayer",
    description: "Cancelled 3 unused subscriptions",
    icon: "Sword",
    unlocked: true,
    unlockedAt: "2026-01-20",
  },
  {
    id: "ach_4",
    title: "Savings Champion",
    description: "Saved $500+ total",
    icon: "Trophy",
    unlocked: true,
    unlockedAt: "2026-03-15",
  },
  {
    id: "ach_5",
    title: "Price Watch",
    description: "Detected 5 price hikes",
    icon: "TrendingUp",
    unlocked: false,
  },
];

export const demoSavingsGoals: SavingsGoal[] = [
  {
    id: "goal_1",
    title: "Cut monthly waste by $100",
    targetAmount: 100,
    currentAmount: 96.96,
    deadline: "2026-08-31",
  },
  {
    id: "goal_2",
    title: "Cancel 2 duplicate subscriptions",
    targetAmount: 2,
    currentAmount: 1,
    deadline: "2026-07-31",
  },
];

export const advisorQuickPrompts = [
  "Where am I wasting money?",
  "How can I save $200/month?",
  "Which subscriptions should I cancel?",
  "What changed this month?",
  "Explain my Leak Score",
  "Generate a cancellation email for Planet Fitness",
];

export const categoryColors: Record<string, string> = {
  streaming: "#ef4444",
  music: "#10b981",
  cloud: "#3b82f6",
  fitness: "#f59e0b",
  insurance: "#6366f1",
  software: "#8b5cf6",
  gaming: "#ec4899",
  news: "#f97316",
  utilities: "#14b8a6",
  loan: "#64748b",
  other: "#6b7280",
};
