"use client";

import { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import { Send, Bot, User, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { advisorQuickPrompts } from "@/lib/demo-data";
import { formatCurrency } from "@/lib/utils";
import type { ChatMessage } from "@/types";

const demoResponses: Record<string, string> = {
  "where am i wasting money?":
    "Based on your data, I've identified **$96.96/month** in potential waste:\n\n1. **Planet Fitness** ($24.99/mo) — Only 8% usage. You visited twice in 90 days.\n2. **Duplicate Music Services** ($21.98/mo) — Spotify (91% usage), plus unused YouTube Music & Apple Music.\n3. **NYT Digital** ($17/mo) — 15% engagement, only 3 articles in 60 days.\n4. **Disney+** ($13.99/mo) — 18% usage while you have Netflix & Prime.\n\nYour biggest leak is unused gym membership followed by duplicate streaming services.",
  "how can i save $200/month?":
    "To save $200/month, here's an aggressive optimization plan:\n\n**Immediate Cancellations ($78.96/mo):**\n- Planet Fitness: $24.99\n- Apple Music + YouTube Music: $21.98\n- NYT Digital: $17.00\n- Disney+: $13.99\n\n**Downgrades ($22/mo):**\n- Netflix Premium → Standard: $7.00\n- Adobe CC → Photography plan: $15.00\n\n**Negotiations ($15/mo):**\n- Adobe retention discount: ~$15\n\n**Cloud Consolidation ($9.99/mo):**\n- Cancel iCloud+ 2TB, keep Google One\n\n**Total potential: $125.95/mo**\n\nTo reach $200, also consider pausing ChatGPT Plus during low-usage months ($20) and switching to annual billing for Spotify (save ~$24/yr).",
  "which subscriptions should i cancel?":
    "Priority cancellation list based on usage data:\n\n🔴 **Cancel Immediately:**\n1. Planet Fitness — 8% usage ($24.99/mo)\n2. Apple Music — 12% usage, duplicate ($10.99/mo)\n3. YouTube Music — 23% usage, duplicate ($10.99/mo)\n\n🟡 **Strong Candidates:**\n4. NYT Digital — 15% usage ($17/mo)\n5. Disney+ — 18% usage ($13.99/mo)\n6. iCloud+ 2TB — duplicate cloud storage ($9.99/mo)\n\n🟢 **Keep:**\n- Spotify (91% usage)\n- ChatGPT Plus (88% usage)\n- Netflix (72% usage despite price hike)",
  "what changed this month?":
    "Here's your July 2026 spending analysis:\n\n📈 **Spending up 5.8%** vs June ($216.90 vs $205.10)\n\n**Changes detected:**\n- Netflix charged new price: $22.99 (was $15.49) — +$7.50 impact\n- New ChatGPT Plus charge: $20.00 (first month)\n- Adobe CC increased: $54.99 (was $52.99) — +$2.00\n\n**New subscriptions:** 1 (ChatGPT Plus)\n**Cancelled:** 0\n**Price hikes:** 2\n\nYour Leak Score dropped from 48 to 42 this month due to increased spending and new subscriptions.",
  "explain my leak score":
    "Your **Leak Score is 42/100** (Needs Attention). Here's the breakdown:\n\n📊 **Component Scores:**\n- Unused Subscriptions: 28/100 ⚠️\n- Duplicate Subscriptions: 35/100 ⚠️\n- Price Hikes: 52/100\n- Large Expenses: 45/100\n- Spending Trend: 38/100 ⚠️\n\n**Key Issues:**\n1. 3 duplicate subscription groups costing $59.95/mo\n2. Netflix price increased 48.4% ($7.50/mo impact)\n3. Planet Fitness at 8% usage — pure waste\n4. Monthly spend up 23% over 6 months\n\n**To improve to 70+:** Cancel duplicates ($59.95), downgrade Netflix ($7), cancel gym ($24.99). This alone would boost your score to ~68.",
};

function getResponse(input: string): string {
  const normalized = input.toLowerCase().trim();
  for (const [key, response] of Object.entries(demoResponses)) {
    if (normalized.includes(key.slice(0, 20)) || key.includes(normalized.slice(0, 20))) {
      return response;
    }
  }
  if (normalized.includes("cancel") && normalized.includes("email")) {
    return `Here's a cancellation email for Planet Fitness:\n\n---\n\n**Subject:** Membership Cancellation Request\n\nDear Planet Fitness Member Services,\n\nI am writing to formally request the cancellation of my membership (Member ID: PF-48291) effective immediately.\n\nDespite my intention to maintain an active lifestyle, I have been unable to utilize the gym facilities regularly due to schedule changes. Per my membership agreement, I understand the cancellation policy and am providing this notice accordingly.\n\nPlease confirm the cancellation in writing and ensure no further charges are applied to my account ending in •••• 4821.\n\nThank you for your assistance.\n\nSincerely,\nAlex Morgan\n\n---\n\n*Generated by LeakGuard AI. Review before sending.*`;
  }
  return `Based on your financial data, you're spending **${formatCurrency(216.9)}/month** across 12 active subscriptions with **${formatCurrency(96.96)}/month** in potential savings.\n\nYour Leak Score of **42** indicates significant optimization opportunities. The top actions I'd recommend:\n\n1. Cancel unused gym membership (save $24.99/mo)\n2. Consolidate music streaming to Spotify only (save $21.98/mo)\n3. Review Netflix downgrade options (save $7/mo)\n\nWould you like me to dive deeper into any of these areas?`;
}

export function AIAdvisorChat() {
  const [messages, setMessages] = useState<ChatMessage[]>([
    {
      id: "welcome",
      role: "assistant",
      content:
        "Hi Alex! I'm your AI Financial Advisor. I've analyzed your 12 subscriptions and found $96.96/month in potential savings. What would you like to know?",
      timestamp: new Date().toISOString(),
      suggestions: advisorQuickPrompts.slice(0, 4),
    },
  ]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);
  const scrollRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, isTyping]);

  const sendMessage = async (text: string) => {
    if (!text.trim()) return;

    const now = Date.now();
    const userMsg: ChatMessage = {
      id: `user_${now}`,
      role: "user",
      content: text,
      timestamp: new Date(now).toISOString(),
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    await new Promise((r) => setTimeout(r, 1200 + Math.random() * 800));

    const replyTime = Date.now();
    const assistantMsg: ChatMessage = {
      id: `assistant_${replyTime}`,
      role: "assistant",
      content: getResponse(text),
      timestamp: new Date(replyTime).toISOString(),
    };
    setMessages((prev) => [...prev, assistantMsg]);
    setIsTyping(false);
  };

  return (
    <Card className="flex flex-col h-[calc(100vh-12rem)]">
      <CardHeader className="border-b border-white/5 shrink-0">
        <div className="flex items-center gap-3">
          <div className="rounded-xl bg-gradient-to-br from-indigo-500 to-purple-600 p-2">
            <Sparkles className="h-5 w-5 text-white" />
          </div>
          <div>
            <CardTitle className="text-base">AI Financial Advisor</CardTitle>
            <p className="text-xs text-muted-foreground">Powered by Gemini • Uses your real data</p>
          </div>
        </div>
      </CardHeader>

      <CardContent className="flex-1 flex flex-col p-0 overflow-hidden">
        <div ref={scrollRef} className="flex-1 overflow-y-auto p-6 space-y-4 scrollbar-thin">
          {messages.map((msg) => (
            <motion.div
              key={msg.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className={`flex gap-3 ${msg.role === "user" ? "justify-end" : ""}`}
            >
              {msg.role === "assistant" && (
                <div className="rounded-lg bg-indigo-500/20 p-2 h-fit shrink-0">
                  <Bot className="h-4 w-4 text-indigo-400" />
                </div>
              )}
              <div
                className={`max-w-[80%] rounded-xl px-4 py-3 text-sm ${
                  msg.role === "user"
                    ? "bg-indigo-500/20 text-foreground"
                    : "bg-secondary/50"
                }`}
              >
                <div className="whitespace-pre-wrap">{msg.content}</div>
                {msg.suggestions && (
                  <div className="flex flex-wrap gap-2 mt-3">
                    {msg.suggestions.map((s) => (
                      <button
                        key={s}
                        onClick={() => sendMessage(s)}
                        className="text-xs px-3 py-1.5 rounded-full bg-indigo-500/10 text-indigo-300 hover:bg-indigo-500/20 transition-colors border border-indigo-500/20"
                      >
                        {s}
                      </button>
                    ))}
                  </div>
                )}
              </div>
              {msg.role === "user" && (
                <div className="rounded-lg bg-secondary p-2 h-fit shrink-0">
                  <User className="h-4 w-4" />
                </div>
              )}
            </motion.div>
          ))}
          {isTyping && (
            <div className="flex gap-3">
              <div className="rounded-lg bg-indigo-500/20 p-2 h-fit">
                <Bot className="h-4 w-4 text-indigo-400" />
              </div>
              <div className="bg-secondary/50 rounded-xl px-4 py-3">
                <div className="flex gap-1">
                  {[0, 1, 2].map((i) => (
                    <motion.div
                      key={i}
                      className="h-2 w-2 rounded-full bg-indigo-400"
                      animate={{ opacity: [0.3, 1, 0.3] }}
                      transition={{ duration: 1, repeat: Infinity, delay: i * 0.2 }}
                    />
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="border-t border-white/5 p-4 shrink-0">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              sendMessage(input);
            }}
            className="flex gap-2"
          >
            <Input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Ask about your subscriptions, savings, or spending..."
              className="flex-1 bg-secondary/30"
              disabled={isTyping}
            />
            <Button type="submit" variant="gradient" size="icon" disabled={isTyping || !input.trim()}>
              <Send className="h-4 w-4" />
            </Button>
          </form>
        </div>
      </CardContent>
    </Card>
  );
}
