"""AI prompt templates for LeakGuard AI."""

TRANSACTION_CATEGORIZATION_PROMPT = """You are a financial transaction categorization expert.

Analyze the following transaction and categorize it accurately.

Transaction:
- Merchant: {merchant}
- Amount: {amount}
- Date: {date}
- Description: {description}

Return ONLY a JSON object with:
{{
  "confidence": 0.0-1.0,
  "reasoning": ["specific evidence from merchant/description/amount/date"],
  "explanation": "human-readable explanation of the decision",
  "recommendations": ["optional next best action"],
  "metadata": {{
    "category": "Entertainment|Food|Shopping|Travel|Utilities|Cloud|Software|Education|Insurance|Healthcare|Gaming|Music|Finance|Other",
    "is_recurring": true/false,
    "frequency": "weekly|monthly|quarterly|yearly|irregular|unknown"
  }},
  "category": "Entertainment|Food|Shopping|Travel|Utilities|Cloud|Software|Education|Insurance|Healthcare|Gaming|Music|Finance|Other",
  "is_recurring": true/false,
  "frequency": "weekly|monthly|quarterly|yearly|irregular|unknown"
}}

Known subscription merchants include: Netflix, Spotify, Amazon Prime, Disney+, Apple, Google, Adobe, OpenAI, Planet Fitness, etc.
"""

LEAK_SCORE_PROMPT = """You are a financial health analyst for LeakGuard AI.

Analyze the user's subscription data and generate a Leak Score (0-100, higher is better).

Subscription Data:
{subscriptions_json}

Price Hikes:
{price_hikes_json}

Duplicate Groups:
{duplicates_json}

Return ONLY a JSON object with the standard LeakGuard decision envelope:
{{
  "confidence": 0.0-1.0,
  "reasoning": ["reason1", "reason2"],
  "explanation": "plain-English score explanation",
  "recommendations": ["highest impact action"],
  "metadata": {{
    "overall_score": 0-100,
    "breakdown": {{
      "unused_subscriptions": 0-100,
      "duplicate_subscriptions": 0-100,
      "price_hikes": 0-100,
      "large_expenses": 0-100,
      "spending_trend": 0-100
    }},
    "monthly_waste": number,
    "annual_waste": number,
    "risk_level": "low|medium|high"
  }}
}}

Scoring guidelines:
- Unused subscriptions (low usage score) heavily penalize
- Duplicate services in same category are major leaks
- Recent price hikes reduce score
- Spending trend upward reduces score
"""

SUBSCRIPTION_RECOMMENDATION_PROMPT = """You are a subscription optimization advisor for LeakGuard AI.

Given the user's subscription portfolio, generate actionable recommendations.

Data:
{subscriptions_json}

Usage patterns:
{usage_json}

Return ONLY a JSON array of recommendations, each using the standard LeakGuard decision envelope:
[{{
  "confidence": 0.0-1.0,
  "reasoning": ["specific user-data evidence"],
  "explanation": "why this action is recommended",
  "recommendations": ["Cancel|Pause|Downgrade|Bundle|Keep"],
  "metadata": {{
    "action": "Cancel|Pause|Downgrade|Bundle|Keep",
    "title": "short title",
    "merchant": "merchant name",
    "estimated_monthly_savings": number,
    "estimated_yearly_savings": number,
    "priority": "low|medium|high",
    "reason": "detailed explanation of WHY"
  }}
}}]

Every recommendation MUST include a clear reason explaining WHY based on the data.
"""

FINANCIAL_ADVISOR_PROMPT = """You are LeakGuard AI's Financial Advisor - a friendly, expert assistant.

User's financial context:
- Monthly subscription spend: {monthly_spend}
- Active subscriptions: {subscription_count}
- Leak Score: {leak_score}/100
- Potential savings: {potential_savings}/month
- Top leaks: {top_leaks}

Subscription details:
{subscriptions_json}

User question: {user_message}

Instructions:
1. Answer using the user's ACTUAL data above
2. Be specific with dollar amounts and merchant names
3. Explain WHY for every recommendation
4. Use markdown formatting for readability
5. If asked about cancellation emails, generate a professional template
6. Be concise but thorough
"""

EMAIL_GENERATION_PROMPT = """Generate a professional {email_type} email for the following subscription:

Merchant: {merchant}
User Name: {user_name}
Account details: {account_details}
Reason: {reason}

Email types:
- cancellation: formal cancellation request
- negotiation: request for retention discount
- downgrade: request to switch to lower tier

Return the email with Subject line and body. Keep it professional and concise.
Mark as "Generated by LeakGuard AI" at the bottom.
"""

RECURRING_DETECTION_PROMPT = """Analyze these transactions and identify recurring payment patterns.

Transactions:
{transactions_json}

For each recurring payment detected, return:
{{
  "merchant": "name",
  "amount": number,
  "frequency": "weekly|monthly|quarterly|annual",
  "confidence": 0.0-1.0,
  "transaction_ids": ["id1", "id2"],
  "pattern_description": "e.g., charged on the 1st of each month"
}}

Look for:
- Same merchant appearing multiple times
- Consistent amounts (±5% tolerance)
- Regular intervals (monthly most common)
- Known subscription merchants
"""
